name: Java CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

env:
  MAVEN_OPTS: -Dfile.encoding=utf-8

jobs:
  build:

    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '17', '21' ]
        os: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: maven

      - name: Echo Maven
        run: mvn -v

      - name: Build with Maven
        run: mvn clean package
